### ISSUE TITLE
Error in "Show static info" Section (test_client.ipynb)

### ISSUE THREAD

**Issue by VinsPal** [dasGringuen/assetto_corsa_gym#13]
Hello everyone,
first of all, congratulations on the work presented here.
I followed the entire procedure to install the plugin, excluding the optional parts for screen capture. I also followed the instructions for Configuring Assetto Corsa. I started a Hot Lap in Monza with the BMW Z4 GT3, but when I run the test_client.ipynb script, nothing happens in AC. Specifically, I get the following error in the notebook in the "Show static info" section:

---------------------------------------------------------------------------
timeout                                   Traceback (most recent call last)
Cell In[3], line 1
----> 1 static_info = client.simulation_management.get_static_info()
      2 ac_mod_config = client.simulation_management.get_config()
      4 logger.info("Static info:")

File c:\Users\<users>\AssettoCorsa_gym\assetto_corsa_gym\AssettoCorsaEnv\ac_client.py:46, in SimulationManagement.get_static_info(self)
     45 def get_static_info(self):
---> 46     static_info = eval(self.send_message("get_static_info", wait_response=True))
     47     track_full_name = f"{static_info['TrackName']}"
     48     if static_info['TrackConfiguration']:

File c:\Users\<users>\AssettoCorsa_gym\assetto_corsa_gym\AssettoCorsaEnv\ac_client.py:31, in SimulationManagement.send_message(self, message, wait_response)
     29 s.settimeout(15)
     30 if wait_response:
---> 31     data = s.recv(self.max_msg_size).decode()
     32     return data
     33 else:

timeout: timed out
---------------------------------------------------------------------------

I'm not very experienced, but it seems like the plugin is unable to communicate with AC.
Do you have any idea why this might be happening and any possible solutions?
Thanks!

**Comment by dasGringuen** [comment]
Hi! We just pushed an update. Could you give it a try? It’s probably complaining about missing dependencies on the Windows side.

If you run into any issues, please paste the output of:

```sh
C:\Users\<user>\Documents\Assetto Corsa\logs\py_log.txt
```

Thanks!

**Comment by VinsPal** [comment]
Hi, thanks for the information. I have downloaded the latest updates, but I am still encountering the same error.
Here is the content of the py_log.txt file:
```
2025-04-02 10:53:42,253 - sensors_par - INFO - Starting sensors_par...
2025-04-02 10:53:42,253 - sensors_par - INFO - Python path: C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\acs.exe
2025-04-02 10:53:42,253 - sensors_par - INFO - Base path: C:\Program Files (x86)\Steam\steamapps\common\assettocorsa
2025-04-02 10:53:42,253 - sensors_par - INFO - Python version: 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:35:05) [MSC v.1600 64 bit (AMD64)]
2025-04-02 10:53:42,253 - sensors_par - INFO - Architecture: ('64bit', 'WindowsPE')
2025-04-02 10:53:42,322 - sensors_par - INFO - [MAIN] Started.
2025-04-02 10:53:42,323 - profiler - INFO - Profiler enabled: False C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\profiler\
2025-04-02 10:53:42,324 - sensors_par - INFO - [MAIN] Starting MGR task
2025-04-02 10:53:42,334 - root - INFO - [EGO SERV] Start ego server socket on: 0.0.0.0:2345
2025-04-02 10:53:42,334 - root - INFO - [EGO SERV] Tick 50 Hz Ego: 25 Hz
2025-04-02 10:53:43,325 - sensors_par - INFO - [MGMT SERV] Start simulation management socket on: 0.0.0.0:2347
2025-04-02 10:53:43,326 - sensors_par - INFO - [MGMT SERV] Waiting for connections.
[sensors_par: error] Traceback (most recent call last):
  File "apps/python/sensors_par\sensors_par.py", line 232, in acMain
    config.config_python_env_name)
  File "apps/python/sensors_par\alternative_python.py", line 28, in  __init__
    self.python_executable = self.init_python_interpreter(config_python_executable, config_python_env_name)
  File "apps/python/sensors_par\alternative_python.py", line 63, in init_python_interpreter
    assert os.path.exists(python_executable), "Python executable not found at: {}".format(python_executable)
AssertionError: Python executable not found at: C:\Users\<user>\AppData\Local\anaconda3\envs\p309\python.exe

``` 


I have checked, but the python.exe file is present in the specified folder.

**Comment by dasGringuen** [comment]
I just tried it on my system, and it works fine. The alternative interpreter is disabled by default in the current version, as it is only needed when working with images.

Did you update the files in `C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\apps\python\sensors_par`?  
The current version sets `self.enable_alternative_python_interpreter` to `False` in `config.py`, so you shouldn't be reaching that line.

Let me know!

**Comment by VinsPal** [comment]
Hi Adrian,
you're right, I had still set the `self.enable_alternative_python_interpreter` to `True`. Now it works fine.
Thanks a lot for your support.
